In [1]:
import jax
import jax.numpy as jnp
import jax.scipy as jsp
import numpy as np
from magi import MAGISolver

In [2]:
import warnings
warnings.filterwarnings("error")

In [3]:
def ode(X, theta, t=None):
    V, R = X
    a, b, c = theta
    return jnp.stack([c * (V - V**3/3 + R), -1/c * (V - a + b*R)])

In [4]:
def discretize_data(sample, I, rounded=3):
    '''
    Discretize a dataset at time set I. Rounds times in I to `rounded` decimal places to mitigate floating point errors.
    '''
    I = np.round(I, rounded)
    data_disc = np.full(shape=(len(I), sample.shape[1]), fill_value=np.nan)
    data_disc[:,0] = I
    data_disc[np.isin(data_disc[:,0], sample[:,0])] = sample
    return data_disc

In [5]:
y = np.loadtxt('y.csv', delimiter=',')
data = discretize_data(y, np.arange(0, 20.1, 0.25))
# data[:,2] = np.nan

In [6]:
solver = MAGISolver(ode, data, jnp.ones(3))

In [7]:
solver.theta_init

Array([0.15874049, 0.16702992, 1.904561  ], dtype=float32)

In [9]:
solver.phis

Array([[1.9891791, 1.127136 ],
       [0.4111044, 0.8714581]], dtype=float32)

In [18]:
data

array([[ 0.00000000e+00, -1.01847804e+00,  1.14685711e+00],
       [ 2.50000000e-01,             nan,             nan],
       [ 5.00000000e-01, -4.97033545e-01,  9.77032340e-01],
       [ 7.50000000e-01,             nan,             nan],
       [ 1.00000000e+00,  1.81554159e+00,  1.40337053e+00],
       [ 1.25000000e+00,             nan,             nan],
       [ 1.50000000e+00,  2.29227317e+00,  6.04333441e-01],
       [ 1.75000000e+00,             nan,             nan],
       [ 2.00000000e+00,  2.06144799e+00,  3.76810960e-01],
       [ 2.25000000e+00,             nan,             nan],
       [ 2.50000000e+00,  1.58656256e+00, -1.11637353e-01],
       [ 2.75000000e+00,             nan,             nan],
       [ 3.00000000e+00,  1.46135312e+00, -2.16998175e-01],
       [ 3.25000000e+00,             nan,             nan],
       [ 3.50000000e+00,  1.56826623e+00, -7.80932208e-01],
       [ 3.75000000e+00,             nan,             nan],
       [ 4.00000000e+00,  1.59389484e+00

In [19]:
solver.x_init

Array([[-1.01847804e+00,  1.14685714e+00],
       [-7.57755756e-01,  1.06194472e+00],
       [-4.97033536e-01,  9.77032363e-01],
       [ 6.59254014e-01,  1.19020140e+00],
       [ 1.81554163e+00,  1.40337050e+00],
       [ 2.05390739e+00,  1.00385201e+00],
       [ 2.29227328e+00,  6.04333460e-01],
       [ 2.17686081e+00,  4.90572214e-01],
       [ 2.06144810e+00,  3.76810968e-01],
       [ 1.82400537e+00,  1.32586807e-01],
       [ 1.58656251e+00, -1.11637354e-01],
       [ 1.52395773e+00, -1.64317757e-01],
       [ 1.46135306e+00, -2.16998175e-01],
       [ 1.51480961e+00, -4.98965204e-01],
       [ 1.56826627e+00, -7.80932188e-01],
       [ 1.58108056e+00, -6.94671273e-01],
       [ 1.59389484e+00, -6.08410418e-01],
       [ 1.37563562e+00, -7.24119425e-01],
       [ 1.15737629e+00, -8.39828372e-01],
       [ 1.19732523e+00, -8.84032845e-01],
       [ 1.23727417e+00, -9.28237319e-01],
       [ 7.92235792e-01, -8.63226354e-01],
       [ 3.47197443e-01, -7.98215389e-01],
       [-4.

In [10]:
a = np.random.normal(size=[20, 20])

In [11]:
b = jnp.array(a)

In [12]:
cpu = jax.devices('cpu')[0]

In [13]:
c = b.to_device(cpu)

In [14]:
d = c + c/2

In [15]:
d.device

CpuDevice(id=0)

In [16]:
I = jnp.linspace(0,20)

In [17]:
jnp.argsort(I)

Array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],      dtype=int64)