In [1]:
import jax
import jax.numpy as jnp
import jax.scipy as jsp
import numpy as np
from magi import MAGISolver

In [2]:
import warnings
warnings.filterwarnings("error")

In [3]:
def ode(X, theta, t=None):
    V, R = X
    a, b, c = theta
    return jnp.stack([c * (V - V**3/3 + R), -1/c * (V - a + b*R)])

In [4]:
def discretize_data(sample, I, rounded=3):
    '''
    Discretize a dataset at time set I. Rounds times in I to `rounded` decimal places to mitigate floating point errors.
    '''
    I = np.round(I, rounded)
    data_disc = np.full(shape=(len(I), sample.shape[1]), fill_value=np.nan)
    data_disc[:,0] = I
    data_disc[np.isin(data_disc[:,0], sample[:,0])] = sample
    return data_disc

In [5]:
y = np.loadtxt('y.csv', delimiter=',')
data = discretize_data(y, np.arange(0, 20.1, 0.25))
data[:,1] = np.nan

In [6]:
sigmas = jnp.array([jnp.nan, 0.2])

In [7]:
solver = MAGISolver(ode, data, jnp.ones(3), sigmas=sigmas)

In [27]:
solver.sigmas

Array([[0. ],
       [0.2]], dtype=float32)

In [9]:
solver.theta_init

Array([0.0690557 , 0.38067418, 0.58648443], dtype=float32)

In [10]:
solver.phis

Array([[0.8873433 , 1.4969976 ],
       [0.71961474, 2.5763302 ]], dtype=float32)

In [11]:
 solver.tau.T * jnp.tile(jnp.array([jnp.inf, 1]), (81, 1))

Array([[0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.

In [12]:
data

array([[ 0.00000000e+00,             nan,  1.14685711e+00],
       [ 2.50000000e-01,             nan,             nan],
       [ 5.00000000e-01,             nan,  9.77032340e-01],
       [ 7.50000000e-01,             nan,             nan],
       [ 1.00000000e+00,             nan,  1.40337053e+00],
       [ 1.25000000e+00,             nan,             nan],
       [ 1.50000000e+00,             nan,  6.04333441e-01],
       [ 1.75000000e+00,             nan,             nan],
       [ 2.00000000e+00,             nan,  3.76810960e-01],
       [ 2.25000000e+00,             nan,             nan],
       [ 2.50000000e+00,             nan, -1.11637353e-01],
       [ 2.75000000e+00,             nan,             nan],
       [ 3.00000000e+00,             nan, -2.16998175e-01],
       [ 3.25000000e+00,             nan,             nan],
       [ 3.50000000e+00,             nan, -7.80932208e-01],
       [ 3.75000000e+00,             nan,             nan],
       [ 4.00000000e+00,             nan

In [13]:
solver.x_init

Array([[-4.60496843e-01,  1.14685714e+00],
       [-3.69403183e-01,  1.06194472e+00],
       [-3.70642811e-01,  9.77032363e-01],
       [-3.75679076e-01,  1.19020140e+00],
       [-1.32064879e-01,  1.40337050e+00],
       [ 1.83089375e-01,  1.00385201e+00],
       [ 2.40423188e-01,  6.04333460e-01],
       [ 2.88103163e-01,  4.90572214e-01],
       [ 3.84288490e-01,  3.76810968e-01],
       [ 4.86748576e-01,  1.32586807e-01],
       [ 5.02734482e-01, -1.11637354e-01],
       [ 4.98006821e-01, -1.64317757e-01],
       [ 5.79824030e-01, -2.16998175e-01],
       [ 6.66919291e-01, -4.98965204e-01],
       [ 5.89044213e-01, -7.80932188e-01],
       [ 4.68117833e-01, -6.94671273e-01],
       [ 5.04426122e-01, -6.08410418e-01],
       [ 5.43734789e-01, -7.24119425e-01],
       [ 5.15751421e-01, -8.39828372e-01],
       [ 4.71146017e-01, -8.84032845e-01],
       [ 4.00246441e-01, -9.28237319e-01],
       [ 3.04614037e-01, -8.63226354e-01],
       [ 2.45194584e-01, -7.98215389e-01],
       [ 1.

In [14]:
import matplotlib.pyplot as plt

In [15]:
a = np.random.normal(size=[20, 20])

In [16]:
b = jnp.array(a)

In [17]:
cpu = jax.devices('cpu')[0]

In [18]:
c = b.to_device(cpu)

In [19]:
d = c + c/2

In [20]:
d.device

CpuDevice(id=0)

In [21]:
?jnp.linspace

Signature:
jnp.linspace(
    start: jax.Array | numpy.ndarray | numpy.bool | numpy.number | bool | int | float | complex | jax._src.literals.TypedNdArray,
    stop: jax.Array | numpy.ndarray | numpy.bool | numpy.number | bool | int | float | complex | jax._src.literals.TypedNdArray,
    num: int = 50,
    endpoint: bool = True,
    retstep: bool = False,
    dtype: str | type[Any] | numpy.dtype | jax._src.typing.SupportsDType | None = None,
    axis: int = 0,
    *,
    device: jaxlib._jax.Device | jaxlib._jax.Sharding | None = None,
) -> jax.Array | tuple[jax.Array, jax.Array]
Docstring:
Return evenly-spaced numbers within an interval.

JAX implementation of :func:`numpy.linspace`.

Args:
  start: scalar or array of starting values.
  stop: scalar or array of stop values.
  num: number of values to generate. Default: 50.
  endpoint: if True (default) then include the ``stop`` value in the result.
    If False, then exclude the ``stop`` value.
  retstep: If True, then return a ``(resul

In [22]:
I = jnp.linspace(0,20, 21)

In [23]:
jnp.argsort(I)

Array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20], dtype=int64)

In [24]:
I

Array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.], dtype=float64)

In [25]:
jnp.where(I >= 10, I, jnp.inf)

Array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.], dtype=float64)

In [26]:
jnp.fft.fft(I).shape

(21,)